language: java
cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk8
script: echo "Running verification"
jobs:
  include:
    - stage: Verify whitelist
      install: skip
      script:
        - ./.circleci/verifyWhitelist.sh
        - docker run -d -p 6379:6379 redis
        - sleep 5
        - mvn clean verify -PmavenCentral
